# App Info
ios_app_id                                : 1136800740                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Track your video game backlog, archive & wish list.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Joe Kimberlin-Wyer                                
your_link                                 :                      
your_city                                 : London                                
email_address                             : joe.kw@me.com
facebook_username                         :                                           
instagram_username                        : joe
twitter_username                          : joekw
github_username                           : joekw
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Add Any Game Ever
    description                           : Search for any game you want using the Giant Bomb Wiki database and access all of the related information.
    fontawesome_icon_name                 : gamepad
    
  - title                                 : Track Progress
    description                           : Keep track of all your games and your progress through them.
    fontawesome_icon_name                 : spinner

  - title                                 : Theme Support
    description                           : Switch between dark and light modes and multiple colour themes.
    fontawesome_icon_name                 : adjust

  - title                                 : Quick Actions
    description                           : Use the Swipe Menu or 3D Touch on the images to access quick actions such as rating or changing status.
    fontawesome_icon_name                 : sync

  - title                                 : Custom Images
    description                           : Customise your lists using banner and poster images from your own photo library.
    fontawesome_icon_name                 : images
  
  - title                                 : Automatic Game of the Year Lists
    description                           : Rate your completed games and access an automated list of your top rated games for each year.
    fontawesome_icon_name                 : star

  - title                                 : Notifications
    description                           : Get notifications when your most anticipated games are released.
    fontawesome_icon_name                 : bell

  - title                                 : Charts & Statistics
    description                           : View charts and stats of your ratings, game completions, games per genre, per platform.
    fontawesome_icon_name                 : chart-line

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#1B1F28"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#1B1F28"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
